#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"

# The 13 permissions Discord mode needs, as Discord's bitfield. Keep this in
# step with the table below and with scripts/discord-smoke-test.ts.
#   MANAGE_CHANNELS 1<<4          a category per repo, a channel per map
#   ADD_REACTIONS 1<<6            acknowledge a message without a new one
#   VIEW_CHANNEL 1<<10            see the channels it makes
#   SEND_MESSAGES 1<<11           the ticket post
#   MANAGE_MESSAGES 1<<13         pin the ticket post
#   EMBED_LINKS 1<<14             ticket status as an embed
#   ATTACH_FILES 1<<15            hand a file back to the human
#   READ_MESSAGE_HISTORY 1<<16    read a thread it was not watching
#   MANAGE_ROLES 1<<28            make a closed map's channel read-only
#   MANAGE_THREADS 1<<34          archive a thread
#   CREATE_PUBLIC_THREADS 1<<35   a thread per ticket
#   CREATE_PRIVATE_THREADS 1<<36  kept for a private map
#   SEND_MESSAGES_IN_THREADS 1<<38  every Claude turn
PERMISSIONS=395405552720

banner "Discord mode — bot and test server"

# ──────────────────────────────────────────────────────────────────────────
stage "A private test server"
say "Discord mode needs a server of your own to build channels in."
say "Do this in the Discord app, not the developer site."
open_url "https://discord.com/channels/@me"
step "In the left sidebar, press + (Add a Server)."
step "Choose 'Create My Own', then 'For me and my friends'."
step "Name it something like 'cmux-wayfinder dev', then press Create."
say ""
say "Now switch on the setting that shows Discord's internal ids:"
step "Press the gear (User Settings), bottom left."
step "Open 'Advanced', then turn 'Developer Mode' on. Close settings."
step "Right-click your new server's icon, then 'Copy Server ID'."
note "A Server ID is 17-20 digits. Discord calls it a guild id in its API."
ask DISCORD_TEST_GUILD_ID "Paste the Server ID:"
write_env DISCORD_TEST_GUILD_ID "$DISCORD_TEST_GUILD_ID"

# ──────────────────────────────────────────────────────────────────────────
stage "The Discord application"
say "An application is the identity your bot speaks as."
open_url "https://discord.com/developers/applications"
step "Press 'Create App', top right."
step "Name it 'cmux-wayfinder', agree to the terms, then press Create."
step "You land on 'General Information'. Find 'Application ID' and copy it."
note "The bot user comes with the application — there is nothing to add."
ask DISCORD_APPLICATION_ID "Paste the Application ID:"
write_env DISCORD_APPLICATION_ID "$DISCORD_APPLICATION_ID"

# ──────────────────────────────────────────────────────────────────────────
stage "The bot token"
say "The token is the bot's password. Discord shows it once, then never again."
if _existing DISCORD_BOT_TOKEN >/dev/null 2>&1; then
  note "A token is already saved. Press Enter at the prompt to keep it, and"
  note "skip the reset below — a reset makes the saved token stop working."
fi
open_url "https://discord.com/developers/applications/$DISCORD_APPLICATION_ID/bot"
step "Under 'Token', press 'Reset Token' and confirm."
step "Press 'Copy'."
warn "Do not paste this token into a chat, an issue, or a commit."
note "It is written to $ENV_FILE, which .gitignore already excludes."
ask_secret DISCORD_BOT_TOKEN "Paste the bot token (hidden):"
write_env DISCORD_BOT_TOKEN "$DISCORD_BOT_TOKEN"

# ──────────────────────────────────────────────────────────────────────────
stage "Intents — what the bot is allowed to see"
say "Stay on the Bot page. Scroll to 'Privileged Gateway Intents'."
open_url "https://discord.com/developers/applications/$DISCORD_APPLICATION_ID/bot"
step "Turn 'MESSAGE CONTENT INTENT' ON."
step "Leave 'PRESENCE INTENT' and 'SERVER MEMBERS INTENT' off."
step "Scroll up and turn 'PUBLIC BOT' OFF, so only you can invite it."
step "Press 'Save Changes'."
note "Message Content is what lets the bot read what you type. Without it,"
note "every message arrives empty and no Claude turn can start."
note "Server Members waits on the multi-user tickets; you can turn it on"
note "later without inviting the bot again."
say ""
say "Two more intents need no toggle — they are on by default:"
note "GUILDS (channels and threads) and GUILD_MESSAGES (a message arrived)."
pause "Saved? Press Enter."

# ──────────────────────────────────────────────────────────────────────────
stage "Invite the bot to the test server"
say "This link already carries the exact permissions Discord mode needs,"
say "so there is nothing to tick on the consent screen."
note "permissions=$PERMISSIONS · scopes: bot, applications.commands"
open_url "https://discord.com/oauth2/authorize?client_id=$DISCORD_APPLICATION_ID&scope=bot%20applications.commands&permissions=$PERMISSIONS&integration_type=0"
step "Pick your test server from the dropdown, then press Continue."
step "Leave every permission ticked, then press Authorize."
step "Solve the captcha if one appears."
warn "Do not grant Administrator. The exact permission set is an answer this map needs."
pause "Bot in the server? Press Enter."

# ──────────────────────────────────────────────────────────────────────────
stage "Prove it works"
say "This probe builds one of everything Discord mode needs, then deletes it:"
note "a category, a text channel, a ticket post, a thread, a forum post,"
note "and a read-only channel — plus a gateway connection with the intents."
say ""
if ! command -v bun >/dev/null 2>&1; then
  warn "bun is not on PATH — install it, then run the probe by hand."
  SKIPPED+=("smoke test: bun scripts/discord-smoke-test.ts")
elif DISCORD_BOT_TOKEN="$DISCORD_BOT_TOKEN" \
     DISCORD_APPLICATION_ID="$DISCORD_APPLICATION_ID" \
     DISCORD_TEST_GUILD_ID="$DISCORD_TEST_GUILD_ID" \
     bun "$REPO_ROOT/scripts/discord-smoke-test.ts"; then
  say "Provisioning is done. Record the ids on the ticket."
else
  warn "The probe failed. Read the failing line above — it names the toggle to fix."
  note "Fix it, then run: bun scripts/discord-smoke-test.ts"
  SKIPPED+=("smoke test failed — re-run bun scripts/discord-smoke-test.ts")
fi
pause "Press Enter for the summary."
# ──────────────────────────────────────────────────────────────────────────

finish
